# Generated by Django 5.1.1 on 2024-09-30 06:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('status', models.IntegerField(default=0)),
                ('personal', models.BooleanField(default=False, null=True)),
                ('settings', models.JSONField(default=dict, null=True)),
                ('created_at', models.BigIntegerField(null=True)),
                ('updated_at', models.BigIntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=500, null=True)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='api.organisation')),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(default=0)),
                ('settings', models.JSONField(default=dict, null=True)),
                ('created_at', models.BigIntegerField(null=True)),
                ('updated_at', models.BigIntegerField(null=True)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='api.organisation')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='api.role')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=255, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('profile', models.JSONField(default=dict)),
                ('status', models.IntegerField(default=0)),
                ('settings', models.JSONField(default=dict, null=True)),
                ('created_at', models.BigIntegerField(null=True)),
                ('updated_at', models.BigIntegerField(null=True)),
                ('organisations', models.ManyToManyField(related_name='users', through='api.Member', to='api.organisation')),
            ],
        ),
        migrations.AddField(
            model_name='member',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='api.user'),
        ),
    ]
